routes:
  event-discovery:
    wsEndpoint: https://ws.svil.inps/host/ArcaNotificaEventiWS
  event-details:
    wsEndpoint: https://ws.svil.inps/host/ArcaIntraNewWS/services/ArcaIntraNewWS
  event-finalizer:
    wsEndpoint: https://ws.svil.inps/host/ArcaNotificaEventiWS

camel:
  springboot:
    main-run-controller: false
    tracing: false
    backlog-tracing: false
    use-breadcrumb: false

server:
  port: 8080

spring:
  jmx:
    enabled: true
  profiles:
    active: test
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: admin
    password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.jdbc.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false

logging:
  level:
    org.springframework.web: INFO
