routes:
  event-discovery:
    interval: 50000
    wsEndpoint: https://ws.svil.inps/host/ArcaNotificaEventiWS
    outputQueueName: EVENTS_PENDING
  event-details:
    interval: 4000
    inputQueueName: EVENTS_PENDING
  event-finalizer:
    interval: 5000
    wsEndpoint: https://ws.svil.inps/host/ArcaNotificaEventiWS

camel:
  springboot:
    main-run-controller: false
    tracing: false
    backlog-tracing: false
    use-breadcrumb: false

management:
  server:
    port: 8912
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - jolokia

server:
  port: 8080


spring:
  jmx:
    enabled: true
  profiles:
    active: dev
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: admin
    password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.jdbc.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false

jms:
  queue:
    destination: demoQueue


logging:
  level:
    org.springframework.web: INFO
